### ISSUE TITLE
PNG didnt convert

### ISSUE THREAD

**Issue by Grimblag** [cadars/portable-php#4]
It seems that png images didnt convert to base64, so that the full url is still in code and will change to windows own index-files/image.png when saving the result page. Didnt check jpgs, ico/favicon works fine.

Test system: Win 10/Firefox, both latest.

**Comment by cadars** [comment]
What's your PHP version? Also, an example image could be useful to reproduce the issue.

**Comment by Grimblag** [comment]
I tested random images, jpg and png from the net.
PHP Version 7.4.28

Thanks for your time! :)

**Comment by cadars** [comment]
I tested various images, with PHP 7.4.21 and 8.0.8, and can’t reproduce the error… a wild guess: is your images folder readable?

**Comment by Grimblag** [comment]
Yes it is. Very strange. Will start again from beginning next days. May the logs will give out more infos. Anyway, thanks for checking.
