### ISSUE TITLE
Strange markdown preview when copying file or text as opposed to typing it from scratch

### ISSUE THREAD

**Issue by agichim** [cadars/portable-php#6]
Hi there,

So was looking into this repo to make a small poem blog. 

I ran into this funny issue. I get line spaces between each line of text and when there is an empty space in the raw markdown, the last two lines don't have that extra space. Below are steps and then screenshots. Keep in mind, the text is formatted as a standard poem, short lines one below another. 

My .md files come from Obsidian and I use VSCodium with portable-php. I did the following and always had the same issue:
- copied the .md file into `/content`
- copied the text straight into the same copied .md file
- copied the text into an existing .md file from this repo
- copied the text into a newly created .md file inside VSCodium.
- copied the text as markdown preview and as raw markdown

I tried implementing double spaces at the end of each line, tried creating a new line with Shift+Enter (which shouldn't make a difference for md), tried using a single space at the end of each line.

The issue doesn't occur when typing the text from scratch in any of the file instances mentioned above.
EDIT: The issue occurs anyway now, nothing that I know of changed, I tested this as I was writing this issue.

Anyway, here are screenshots:
raw markdown
![raw markdown](https://github.com/cadars/portable-php/assets/51931067/80568250-8ce5-4fc1-a843-07cec109ef4b)
preview in portable-php
![preview in portable-php](https://github.com/cadars/portable-php/assets/51931067/672dc5fa-5c82-42f0-a1fc-e143c6f2522c)

What do you think?

**Comment by agichim** [comment]
So what the script does, it adds a `<br>` after each line, but the break sometimes acts as a wider space sometimes it doesn't, in the case of the last two lines.

**Comment by cadars** [comment]
There are way too many ways to encode a line break :) https://learn.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks?view=vs-2022

Maybe removing line [47](https://github.com/cadars/portable-php/blob/main/portable.php#L47C26-L47C26) and using two double spaces at the end of each line would solve the issue?

**Comment by agichim** [comment]
So removing line 47 didn't solve it. Everything stays the same. 

I think any changed need to be made  somewhere in the Parsedown files.

Inspecting the elements, the second line has for some odd reason a margin-top. 

![image](https://github.com/cadars/portable-php/assets/51931067/bffd1931-51b2-455a-b8de-38810b54b947)

**Comment by agichim** [comment]
I found a solution by commenting out this:

```
section * + * {
  margin-top: .9em;
}
```

It's what gives that margin-top. I'll leave it like this and see if I run into other issues.

**Comment by cadars** [comment]
Maybe this would be better then:

```css
section > * + * {
  margin-top: .9em;
}
```
